apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: store-inventory
  name: finn15-store-inventory-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: finn15
    server: https://kubernetes.default.svc
  project: finn15
  source:
    path: lab3-4/apps/store-inventory/overlays
    repoURL: https://github.com/natarajan-k/eda-tech-academy-new.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
