apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: item-inventory
  name: finn15-item-inventory-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: finn15
    server: https://kubernetes.default.svc
  project: finn15
  source:
    path: lab3-4/apps/item-inventory/overlays
    repoURL: https://github.com/natarajan-k/eda-tech-academy-new.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

